name: firebase_notifications_handler
description: Simple notifications handler which provides callbacks like onTap which really make it easy to handle notification taps and a lot more.
version: 0.0.2
homepage: https://github.com/rithik-dev/firebase_notifications_handler

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
